<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Arena.AI.Trainer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Arena.AI.Core\Arena.AI.Core.csproj" />
    <ProjectReference Include="..\Arena.AI\Arena.AI.csproj" />
  </ItemGroup>
</Project>
